name: Convert Bicep to JSON

on:
 
  workflow_dispatch:   

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: bicep-build-output
        uses: Azure/bicep-build-action@v1.0.1
        with:
          bicepFilePath: ./misc/new-storage-account.bicep
          outputFilePath: ./misc/new-storage-account.json
              
