name: Convert Bicep to JSON

on:
  workflow_dispatch:   

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: bicep-build-output
        uses: Azure/bicep-build-action@v1.0.1
        with:
          bicepFilePath: ./misc/new-storage-account.bicep
          outputFilePath: ./misc/new-storage-account.json

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add ./misc/new-storage-account.json
          git commit -m 'Update new-storage-account.json'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
